org: anzar
app: youtube-url-service
service: youtube-url-service

frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  stage: serverless-admin
  region: us-east-1
  lambdaHashingVersion: 20201221
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "*"


functions:
  candidateSubmission:
    handler: api/url.submit
    memorySize: 128
    description: Submit url of youtube video .
    events:
      - http:
          path: url
          method: post

  create:
    handler: api/candidate.submit
    memorySize: 128
    description: Submit data .
    events:
      - http:
          path: candidate
          method: post
          cors: true

  listCandidates:
    handler: api/candidate.list
    memorySize: 128
    description: List all candidates
    events:
      - http: 
          path: candidates
          method: get

  candidateDetails:
    handler: api/candidate.get
    events:
      - http:
          path: candidates/{id}
          method: get

resources:
  Resources:
    CandidatesDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: "id"
            AttributeType: "S"   
        KeySchema:
          -
            AttributeName: "id"
            KeyType: "HASH"
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        StreamSpecification:
          StreamViewType: "NEW_AND_OLD_IMAGES"
        TableName: youtube_user_details


